--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/zFrozead0s/Easy-Crates
build-by-default: true
branches:
  - main
projects:
  Easy-Crates:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.3
      - src: DavyCraft648/PMServerUI/PMServerUI
        version: ^1.0.2
...
